version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
    ignore:
      # Ignore updates to packages that start 'k8s'
      # Wildcards match zero or more arbitrary characters
      - dependency-name: "k8s.io*"
