version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "knative.dev/*"
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      k8s:
        update-types: patch
        patterns:
          - "k8s.io/*"
      golang-x:
        patterns:
          - "golang.org/x/*"
