coverage:
  # Commit status https://docs.codecov.io/docs/commit-status are used
  # to block PR based on coverage threshold.
  status:
    project:
      default:
        # https://github.com/knative/pkg/issues/1785
        # Real goal is 80, but prow sees this as a blocker if not met for merging.
        target: 68
        threshold: 1%
    patch:
      # Disable the coverage threshold of the patch, so that PRs are
      # only failing because of overall project coverage threshold.
      # See https://docs.codecov.io/docs/commit-status#disabling-a-status.
      default: false
comment:
  # Just one comment, updated as necessary. Will be recreated if deleted.
  behavior: default
ignore:
  - "**/zz_generated*.go" # Ignore generated files.
  - "codegen/**/*" #TODO: fix coverage
  - "injection/**/*" #TODO: fix coverage
  - "test/**/*"
  - "tracing/**/*" #TODO: fix coverage
  - "client"
  - "hack"
  - "reconciler/testing"
  - "testing"
  - "third_party"
  - "vendor"
