run:
  timeout: 5m

  skip-dirs:
    - injection/client
    - test/mako

linters:
  enable:
    - gosec
    - prealloc
    - unconvert
  disable:
    - errcheck

issues:
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec
