# Copyright 2020 The Knative Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test

on:
  pull_request:
    branches: [ 'main', 'master', 'release-*' ]

jobs:

  nostackdriver:
    name: Unit Tests w/o stackdriver
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test w/nostackdriver
        run: go test -tags=nostackdriver -race ./...
